services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - app-network

  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=topsecret
      - POSTGES_USER=prisma

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
    networks:
      - app-network

  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   container_name: ui
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - API_URL=http://api:8080
  #   depends_on:
  #     - api
  #   networks:
  #     - app-network
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  esdata:
networks:
  app-network:
    driver: bridge
